sudo: required
language: python
notifications:
  email:
    recipients:
      - x94carbone@gmail.com
    on_success: never
    on_failure: always
python:
  - '3.6'
script:
  - coverage run --source=omicron ./test_script.py
after_success: coveralls